version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: financial-dashboard-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - REACT_APP_OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - backend
    networks:
      - financial-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: financial-dashboard-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=5000
    depends_on:
      - mongodb
    networks:
      - financial-network

  mongodb:
    image: mongo:6.0
    container_name: financial-dashboard-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - financial-network

volumes:
  mongodb_data:

networks:
  financial-network:
    driver: bridge